Repository GlueOps/qa-template-basic-app-code-repo, pull requests merged in 2024-10, with the labels that each got.

#8 Update and rename ghcr.yaml to container_image.yaml
  .github/workflows/container_image.yaml
  .github/workflows/ghcr.yaml
Labels: enhancement, configuration changes, Review effort [1-5]: 2

#12 [skip actions] synced file(s) with internal-GlueOps/github-shared-files-sync
  .github/release.yml
Labels: configuration changes, Review effort [1-5]: 1, sync

#10 chore(deps): update httpd docker tag to v2.4.62
  Dockerfile
Labels: patch, auto-update, include-in-release-notes, dependencies, Review effort [1-5]: 1
